matrix:
  include:
    - env: ACTION=iOS
    - env: ACTION=macOS
    - env: ACTION=tvOS
    - env: ACTION=carthage
    - env: ACTION=swiftpm-macOS
    - env: ACTION=swiftpm-linux
      os: linux
      sudo: required
      dist: trusty
      language: generic

os: osx
language: objective-c
osx_image: xcode9

script:
  - make install-$ACTION && make test-$ACTION
